import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Link from "next/link";
import { createSupabaseClient, APP_NAME } from "@nonews/shared";
import type { ArticleWithSource } from "@nonews/ui";
import { authorNameToSlug } from "../../../lib/authorSlug";
import { categoryToSlug } from "../../../lib/topicSlug";
import { getEditorialBySlug } from "./getEditorialBySlug";
import { getRelatedArticles } from "./getRelatedArticles";
import { EditorialCardClient } from "./EditorialCardClient";
import { RelatedInsights } from "./RelatedInsights";

/** ISR: revalidate every 1 hour so the page stays fresh without hitting the DB on every request. */
export const revalidate = 3600;

type Props = {
  params: Promise<{ slug: string }>;
};

/**
 * Pre-renders all completed editorial slugs at build time for better SEO and first-load.
 * New articles are still served on-demand and then cached per revalidate.
 */
export async function generateStaticParams() {
  const supabase = createSupabaseClient();
  const { data } = await supabase
    .from("articles")
    .select("id")
    .eq("status", "completed");
  const rows = (data ?? []) as { id: string }[];
  return rows.map((row) => ({ slug: row.id }));
}

/** Article row with source_id and source category for related-articles logic. */
type EditorialRow = ArticleWithSource & {
  source_id?: string;
  sources?: { name: string; category?: string } | null;
};

/**
 * Fetches editorial for the page (full fields for SummaryCard) plus source_id and category for related insights.
 */
async function getEditorialForPage(slug: string) {
  const supabase = createSupabaseClient();
  const { data, error } = await supabase
    .from("articles")
    .select("id, title, link, author, published_at, ai_summary, ai_simplified_summary, ai_stance, source_id, sources(name, category)")
    .eq("id", slug)
    .eq("status", "completed")
    .single();

  if (error || !data) return null;
  return data as EditorialRow;
}

/**
 * Title: [Editorial Title] - Summary & Analysis | YourAppName.
 * Description: First 150 characters of ai_summary.
 * OpenGraph: Dynamic OG image (Author + Stance) via opengraph-image.tsx.
 * Canonical: Full URL for the page to prevent duplicate content.
 */
export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params;
  const editorial = await getEditorialBySlug(slug);
  if (!editorial) {
    return { title: "Editorial not found" };
  }

  const title = `${editorial.title} - Summary & Analysis | ${APP_NAME}`;
  const description = editorial.ai_summary
    ? editorial.ai_summary.slice(0, 150).trim() + (editorial.ai_summary.length > 150 ? "…" : "")
    : undefined;

  const canonicalPath = `/editorials/${slug}`;

  return {
    title,
    description,
    openGraph: {
      title,
      description: description ?? undefined,
      type: "article",
      url: canonicalPath,
      /** Dynamic OG image (Author + Stance) is generated by opengraph-image.tsx in this segment. */
    },
    twitter: {
      card: "summary_large_image",
      title,
      description: description ?? undefined,
    },
    alternates: {
      canonical: canonicalPath,
    },
  };
}

export default async function EditorialPage({ params }: Props) {
  const { slug } = await params;
  const article = await getEditorialForPage(slug);
  if (!article) notFound();

  const authorSlug = article.author ? authorNameToSlug(article.author) : null;
  const sourceId = article.source_id ?? "";
  const category = article.sources?.category ?? "";
  const related = await getRelatedArticles(
    article.id,
    article.author ?? null,
    sourceId,
    category
  );

  return (
    <main className="mx-auto max-w-2xl px-4 py-8">
      <p className="mb-6">
        <Link href="/" className="text-sm font-medium text-slate-600 hover:text-slate-900">
          ← Today&apos;s Edition
        </Link>
      </p>
      <EditorialCardClient article={article} />
      {authorSlug && article.author && (
        <p className="mt-6">
          <Link
            href={`/author/${authorSlug}`}
            className="text-sm font-medium text-slate-600 hover:text-slate-900"
          >
            More summaries by {article.author} →
          </Link>
        </p>
      )}
      <RelatedInsights
        articles={related}
        topicLabel={category || undefined}
        topicSlug={category ? categoryToSlug(category) : undefined}
      />
    </main>
  );
}
