import { useBookmarks } from "../../../hooks/useBookmarks";
import { supabase } from "../../../lib/supabase";
import { SummaryCard, type ArticleWithSource } from "@nonews/ui";
import type { AuthorStance } from "@nonews/shared";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import * as Haptics from "expo-haptics";
import * as WebBrowser from "expo-web-browser";
import { useLocalSearchParams, router } from "expo-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import {
  ActivityIndicator,
  FlatList,
  Image,
  Pressable,
  Share,
  StyleSheet,
  Text,
  View,
} from "react-native";
import Animated, { FadeIn, FadeOut } from "react-native-reanimated";
import { SafeAreaView } from "react-native-safe-area-context";
import { ArrowLeft } from "lucide-react-native";

/** Stance colours for the AI Analysis bar chart (aligned with SummaryCard badges). */
const STANCE_BAR_COLORS: Record<string, string> = {
  Critical: "#ec4899",
  Supportive: "#10b981",
  Balanced: "#f59e0b",
  Sarcastic: "#6366f1",
  Neutral: "#94a3b8",
};
const STANCE_DEFAULT_COLOR = "#94a3b8";

/** Author row from DB. */
interface Author {
  id: string;
  name: string;
  image_url: string | null;
  bio: string | null;
}

const TOAST_DURATION_MS = 2500;
const AI_ANALYSIS_ARTICLE_COUNT = 10;

/**
 * Derives an elegant 1–2 letter monogram from the author's name.
 */
function getMonogram(name: string): string {
  const parts = name.trim().split(/\s+/).filter(Boolean);
  if (parts.length >= 2) {
    return (parts[0][0] + parts[parts.length - 1][0]).toUpperCase();
  }
  if (parts[0]?.length >= 2) {
    return parts[0].slice(0, 2).toUpperCase();
  }
  return parts[0]?.[0]?.toUpperCase() ?? "?";
}

/** Stance label plus share of last N articles (percentage). */
interface StanceShare {
  stance: string;
  count: number;
  percentage: number;
}

/**
 * Computes stance counts and percentages from the last N articles.
 * Used for the AI Analysis bar chart and summary text.
 */
function useStanceBreakdown(
  articles: ArticleWithSource[],
  lastN: number
): StanceShare[] {
  return useMemo(() => {
    const slice = articles.slice(0, lastN);
    const total = slice.length;
    if (total === 0) return [];

    const countByStance: Record<string, number> = {};
    for (const a of slice) {
      const label = (a.ai_stance as AuthorStance) ?? "Neutral";
      countByStance[label] = (countByStance[label] ?? 0) + 1;
    }

    const shares: StanceShare[] = Object.entries(countByStance)
      .map(([stance, count]) => ({
        stance,
        count,
        percentage: Math.round((count / total) * 100),
      }))
      .filter((s) => s.percentage > 0)
      .sort((a, b) => b.percentage - a.percentage);

    return shares;
  }, [articles, lastN]);
}

function AIAnalysisSection({ stanceShares }: { stanceShares: StanceShare[] }) {
  if (stanceShares.length === 0) return null;

  const summaryText = stanceShares
    .map((s) => `${s.percentage}% ${s.stance}`)
    .join(", ");

  return (
    <View style={styles.aiSection}>
      <Text style={[styles.aiSectionTitle, { fontFamily: "Georgia" }]}>
        AI Analysis
      </Text>
      <Text style={styles.aiSummaryText}>{summaryText}</Text>
      <View style={styles.barContainer}>
        {stanceShares.map(({ stance, percentage }) => (
          <View
            key={stance}
            style={[
              styles.barSegment,
              {
                width: `${percentage}%`,
                backgroundColor:
                  STANCE_BAR_COLORS[stance] ?? STANCE_DEFAULT_COLOR,
              },
            ]}
          />
        ))}
      </View>
      <Text style={styles.aiDisclaimer}>
        Tone analysis generated by AI based on recent editorials.
      </Text>
    </View>
  );
}

export default function AuthorProfileScreen() {
  const { id: rawId } = useLocalSearchParams<{ id: string }>();
  const authorId = typeof rawId === "string" ? rawId : rawId?.[0];
  const queryClient = useQueryClient();
  const { toggleBookmark, isBookmarked } = useBookmarks();
  const [toastMessage, setToastMessage] = useState<string | null>(null);
  const [isFollowing, setIsFollowing] = useState(false);

  const { data: author, isLoading: authorLoading, error: authorError } = useQuery({
    queryKey: ["author", authorId],
    queryFn: async () => {
      if (!authorId) throw new Error("No author ID");
      const { data, error } = await supabase
        .from("authors")
        .select("id, name, image_url, bio")
        .eq("id", authorId)
        .single();
      if (error) throw error;
      return data as Author;
    },
    enabled: !!authorId,
  });

  const { data: articles = [], isLoading: articlesLoading } = useQuery({
    queryKey: ["author-articles", authorId],
    queryFn: async () => {
      if (!authorId) return [];
      const { data, error } = await supabase
        .from("articles")
        .select("id, title, link, author, published_at, ai_summary, ai_simplified_summary, ai_stance, sources(name)")
        .eq("author_id", authorId)
        .eq("status", "completed")
        .order("published_at", { ascending: false });
      if (error) throw error;
      return (data ?? []) as ArticleWithSource[];
    },
    enabled: !!authorId,
  });

  const { data: followRow } = useQuery({
    queryKey: ["follow", authorId],
    queryFn: async () => {
      const { data: { session } } = await supabase.auth.getSession();
      if (!session?.user || !authorId) return null;
      const { data } = await supabase
        .from("follows")
        .select("user_id, author_id")
        .eq("user_id", session.user.id)
        .eq("author_id", authorId)
        .maybeSingle();
      return data;
    },
    enabled: !!authorId && !!author,
  });

  useEffect(() => {
    setIsFollowing(!!followRow);
  }, [followRow]);

  useEffect(() => {
    if (!toastMessage) return;
    const t = setTimeout(() => setToastMessage(null), TOAST_DURATION_MS);
    return () => clearTimeout(t);
  }, [toastMessage]);

  const handleFollow = useCallback(async () => {
    const { data: { session } } = await supabase.auth.getSession();
    if (!session?.user) {
      router.push("/login");
      return;
    }
    if (!authorId || !author) return;

    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);

    if (isFollowing) {
      await supabase
        .from("follows")
        .delete()
        .eq("user_id", session.user.id)
        .eq("author_id", authorId);
      setIsFollowing(false);
      queryClient.invalidateQueries({ queryKey: ["follow", authorId] });
      return;
    }

    const { error } = await supabase.from("follows").insert({
      user_id: session.user.id,
      author_id: authorId,
    });
    if (error) return;

    setIsFollowing(true);
    queryClient.invalidateQueries({ queryKey: ["follow", authorId] });
    setToastMessage(`You are now following ${author.name}`);
  }, [authorId, author, isFollowing, queryClient]);

  const handleReadFull = useCallback((url: string) => {
    WebBrowser.openBrowserAsync(url, {
      presentationStyle: WebBrowser.WebBrowserPresentationStyle.PAGE_SHEET,
    });
  }, []);

  const renderItem = useCallback(
    ({ item }: { item: ArticleWithSource }) => (
      <SummaryCard
        item={item}
        onReadFull={handleReadFull}
        isBookmarked={isBookmarked(item.id)}
        onToggleBookmark={() => toggleBookmark(item.id)}
        onShare={() => {
          const message = [item.title, item.ai_summary ?? "", item.link].filter(Boolean).join("\n\n") || item.link;
          Share.share({ title: item.title, message, url: item.link });
        }}
        onExplainRequested={async (articleId) => {
          const { data, error } = await supabase.functions.invoke("simplify-summary", {
            body: { articleId },
          });
          if (error) return null;
          return (data?.simplified as string) ?? null;
        }}
      />
    ),
    [handleReadFull, isBookmarked, toggleBookmark]
  );

  const keyExtractor = useCallback((item: ArticleWithSource) => item.id, []);

  if (!authorId) {
    return (
      <SafeAreaView style={styles.safeArea} edges={["top"]}>
        <View style={styles.centered}>
          <Text style={styles.errorText}>Invalid author link.</Text>
        </View>
      </SafeAreaView>
    );
  }

  if (authorLoading || (author && articlesLoading && articles.length === 0)) {
    return (
      <SafeAreaView style={styles.safeArea} edges={["top"]}>
        <View style={styles.centered}>
          <ActivityIndicator size="large" color="#0f172a" />
          <Text style={styles.loadingText}>Loading profile...</Text>
        </View>
      </SafeAreaView>
    );
  }

  if (authorError || !author) {
    return (
      <SafeAreaView style={styles.safeArea} edges={["top"]}>
        <View style={styles.centered}>
          <Text style={styles.errorText}>Author not found.</Text>
        </View>
      </SafeAreaView>
    );
  }

  const editorialCount = articles.length;
  const monogram = getMonogram(author.name);
  const stanceShares = useStanceBreakdown(articles, AI_ANALYSIS_ARTICLE_COUNT);

  const listHeader = useMemo(
    () => <AIAnalysisSection stanceShares={stanceShares} />,
    [stanceShares]
  );

  return (
    <SafeAreaView style={styles.safeArea} edges={["top"]}>
      <View style={styles.header}>
        <Pressable
          onPress={() => router.back()}
          hitSlop={12}
          style={({ pressed }) => [styles.backButton, pressed && styles.backPressed]}
        >
          <ArrowLeft size={24} color="#0f172a" />
        </Pressable>
        <View style={styles.headerCenter}>
          {author.image_url ? (
            <Image
              source={{ uri: author.image_url }}
              style={styles.avatar}
              accessibilityLabel={`${author.name} headshot`}
            />
          ) : (
            <View style={styles.monogramWrap}>
              <Text style={styles.monogramText}>{monogram}</Text>
            </View>
          )}
          <Text style={[styles.authorName, { fontFamily: "Georgia" }]} numberOfLines={2}>
            {author.name}
          </Text>
          <Text style={styles.stats}>
            {editorialCount} Editorial{editorialCount !== 1 ? "s" : ""}
          </Text>
        </View>
        <Pressable
          onPress={handleFollow}
          style={({ pressed }) => [
            styles.followButton,
            isFollowing && styles.followButtonFollowing,
            pressed && styles.followPressed,
          ]}
        >
          <Text style={[styles.followText, isFollowing && styles.followTextFollowing]}>
            {isFollowing ? "Following" : "Follow"}
          </Text>
        </Pressable>
      </View>

      {articles.length === 0 ? (
        <View style={styles.emptyState}>
          <Text style={[styles.emptyTitle, { fontFamily: "Georgia" }]}>
            No editorials yet
          </Text>
          <Text style={styles.emptySubtitle}>
            Completed pieces by this author will appear here.
          </Text>
        </View>
      ) : (
        <FlatList
          data={articles}
          renderItem={renderItem}
          keyExtractor={keyExtractor}
          ListHeaderComponent={listHeader}
          contentContainerStyle={styles.listContent}
          showsVerticalScrollIndicator={false}
        />
      )}

      {toastMessage ? (
        <Animated.View
          entering={FadeIn.duration(200)}
          exiting={FadeOut.duration(200)}
          style={styles.toast}
        >
          <Text style={styles.toastText}>{toastMessage}</Text>
        </Animated.View>
      ) : null}
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#f8fafc",
  },
  header: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#e2e8f0",
  },
  backButton: {
    alignSelf: "flex-start",
    padding: 4,
    marginBottom: 12,
  },
  backPressed: { opacity: 0.7 },
  headerCenter: {
    alignItems: "center",
  },
  avatar: {
    width: 88,
    height: 88,
    borderRadius: 44,
    marginBottom: 12,
    backgroundColor: "#e2e8f0",
  },
  monogramWrap: {
    width: 88,
    height: 88,
    borderRadius: 44,
    marginBottom: 12,
    backgroundColor: "#0f172a",
    alignItems: "center",
    justifyContent: "center",
  },
  monogramText: {
    fontSize: 28,
    fontWeight: "600",
    color: "#f8fafc",
    fontFamily: "Georgia",
  },
  authorName: {
    fontSize: 22,
    fontWeight: "600",
    color: "#0f172a",
    textAlign: "center",
    marginBottom: 4,
  },
  stats: {
    fontSize: 14,
    color: "#64748b",
    marginBottom: 16,
  },
  followButton: {
    alignSelf: "center",
    paddingVertical: 10,
    paddingHorizontal: 24,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#0f172a",
    backgroundColor: "#0f172a",
  },
  followButtonFollowing: {
    backgroundColor: "transparent",
  },
  followPressed: { opacity: 0.8 },
  followText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#fff",
  },
  followTextFollowing: {
    color: "#0f172a",
  },
  aiSection: {
    marginBottom: 20,
    paddingVertical: 16,
    paddingHorizontal: 4,
    borderBottomWidth: 1,
    borderBottomColor: "#e2e8f0",
  },
  aiSectionTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#0f172a",
    marginBottom: 8,
  },
  aiSummaryText: {
    fontSize: 15,
    color: "#475569",
    marginBottom: 10,
  },
  barContainer: {
    flexDirection: "row",
    height: 10,
    borderRadius: 5,
    overflow: "hidden",
    backgroundColor: "#e2e8f0",
    marginBottom: 10,
  },
  barSegment: {
    height: "100%",
    minWidth: 2,
  },
  aiDisclaimer: {
    fontSize: 12,
    color: "#94a3b8",
    fontStyle: "italic",
  },
  listContent: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 32,
  },
  centered: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 32,
  },
  loadingText: {
    marginTop: 12,
    fontSize: 14,
    color: "#64748b",
  },
  errorText: {
    textAlign: "center",
    color: "#dc2626",
    fontSize: 16,
  },
  emptyState: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 32,
  },
  emptyTitle: {
    fontSize: 18,
    color: "#64748b",
    textAlign: "center",
  },
  emptySubtitle: {
    marginTop: 8,
    fontSize: 14,
    color: "#94a3b8",
    textAlign: "center",
  },
  toast: {
    position: "absolute",
    bottom: 32,
    left: 16,
    right: 16,
    backgroundColor: "#0f172a",
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
  toastText: {
    fontSize: 15,
    fontWeight: "500",
    color: "#fff",
    textAlign: "center",
  },
});
